
<main class="pt-28 px-[9.5vw]">
    <article class="flex justify-between flex-col gap-5 bg-gray-700 rounded-md p-5 col-span-1 row-span-1 fixed w-96">
        <header class="text-center font-medium text-2xl border-b-2 border-gray-600 pb-3">
            <h1>User details</h1>
        </header>
        <description class="overflow-x-auto">
            <form method="post" action="functions/query.php" id="form">
                <div class="flex items-center">
                    <label class="font-medium basis-28">Full Name</label>
                    <input type="text" name="fullname" id="fullnameForm" rows="1" class="col-span-4 block p-2 m-2 w-full text-sm rounded-lg border  dark:bg-gray-600 dark:border-gray-700 dark:text-white"></input>
                </div>
                <div class="flex items-center">
                    <label class="font-medium basis-28">Username</label>
                    <input type="text" name="username" id="usernameForm" rows="1" class="col-span-4 block p-2 m-2 w-full text-sm rounded-lg border  dark:bg-gray-600 dark:border-gray-700 dark:text-white"></input>
                </div>
                <div class="flex items-center">
                    <label class="font-medium basis-28">Role</label>
                    <select name="role" id="roleForm" class="col-span-4 block p-2 m-2 w-full text-sm rounded-lg border dark:bg-gray-600 dark:border-gray-700 dark:text-white">
                        <option disabled selected value></option>
                        <option value="admin">Admin</option>
                        <option value="user">User</option>
                    </select>
                </div>
                <div class="flex items-center">
                    <label class="font-medium basis-28">E-mail</label>
                    <input type="text" name="email" id="emailForm" rows="1" class="col-span-4 block p-2 m-2 w-full text-sm rounded-lg border  dark:bg-gray-600 dark:border-gray-700 dark:text-white"></input>
                </div>
                <div class="flex items-center">
                    <label class="font-medium basis-56">First-time User</label>
                    <input type="checkbox" name="firstTimeUser" id="firstTimeUser" class="col-span-4 block p-2 m-2 w-full text-sm rounded-lg border  dark:bg-gray-600 dark:border-gray-700 dark:text-white"></input>
                </div>

                <!-- FORM SUBMITION -->
                <div class="flex items-center gap-4">
                    <button type="submit" id="formButtonAdmin" class="col-span-1 align-center px-5 py-2.5 mt-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800 shadow-glow-sm shadow-blue-600">Add/Update</button>
                    <?if(isset($_GET["error"])) failure("Query error", $errorIcon, "px-5 py-2.5 mr-2 basis-[21.725rem] ".$errorClass) ?>
                </div>
                
            </form>
        </description>
    </article>

    <div class="grid rounded-md gap-8 w-[98rem] pl-[27rem] ">
        <article class="flex flex-col gap-5 bg-gray-700 rounded-md p-8 ">
            <header class="text-center font-medium text-2xl border-b-2 border-gray-600 pb-3">
                <h1>Users</h1>
                <sup class="text-sm">*defualt password is for example "jarda!"</sup>
            </header>
            <description class="px-10 overflow-x-auto max-h-[32rem]">
            <script src="./assets/scripts/tableActions.js"></script>
                <table class="w-full" id="table">
                    <thead>
                        <tr><th class='border-b p-2 w-52 border-gray-400'>Full Name</th><th class='border-b border-l p-2 w-52 border-gray-400'>Username</th><th class='p-2 border-l border-b w-36 border-gray-400'>Role</th><th class='p-2 border-l border-b border-gray-400'>E-mail</th></tr>
                    </thead>
                    <tbody>
                    <?php
                        include_once('./functions/connectSQL.php');
                        $stmt = $con->prepare("SELECT * FROM users");
                        $stmt->execute();
                        $x = 1;
                        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
                            
                            echo "<tr class='hover:bg-gray-800 cursor-pointer' onClick='returnValues(".$x.");' id='tableRow'><td class='border-t p-2 px-4 border-gray-400' id='fullnameCell'>" .$row["fullname"]  . "</td><td class='border-l border-t p-2 px-4 border-gray-400' id='usernameCell'>".$row["username"]."</td><td class='border-l border-t p-2 px-4 border-gray-400' id='roleCell'>" . $row["role"] . "</td><td class='border-l border-t p-2 px-4 border-gray-400' id='emailCell'>" . $row["email"] . "</td></tr>";
                            $x++;
                        }
                    ?>
                    </tbody>
                </table>

            </description>
        </article>
    </div>
</main>