<main class="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-4 justify-items-center max-w-9xl pt-28 pb-8 m-auto">
    <article class="flex justify-between flex-col gap-5 w-[25rem] min-h-60 max-h-80 bg-gray-700 rounded-md p-5">
        <header>
            <h1 class="flex-1 font-medium text-xl">What's new in version 0.1.6a! 🥳</h1>
        </header>
        <description class="flex-auto overflow-x-auto">
                <li>Hey admins! Now you can add users from application! ⚒️</li>
                <li>We added changelog section to keep eye on versioning and past updates! 👀</li>
                <li>Added more responsiveness on screen resolutions! 📱</li>
                <br>
                
        </description>
        <footer>
            Please report bugs on github!
            <div class="flex justify-between">
                <h4>1/6/2023</h4>
                <h3>v0.1.6a</h3>
            </div>
        </footer>
    </article>

    <article class="flex justify-between flex-col gap-5 w-[25rem] min-h-80 bg-gray-700 rounded-md p-5">
        <header>
            <h1 class="flex-1 font-medium text-xl">What's new in version 0.1.7a! 🥳</h1>
        </header>
        <description class="flex-auto">
                <li>Guess what! Yes you are right! Updating records is now available in admin panel! Hope this helps! ⚒️ </li>
                <li>Changing password on first time login? Sounds interesting! 😍 </li>
        </description>
        <footer>
            Please report bugs on github!
            <div class="flex justify-between">
                <h4>1/9/2023</h4>
                <h3>v0.1.7a</h3>
            </div>
        </footer>
    </article>
</main>