<main class="flex pt-28 pl-10">
    
    <aside class="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-10 justify-items-center">
        <article class="flex justify-between flex-col gap-5 max-w-[25rem] min-h-80 max-h-80 bg-gray-700 rounded-md p-5">
            <header>
                <h1 class="flex-1 font-medium text-xl">What's new in version 0.0.6x! 🥳</h1>
            </header>
            <description class="flex-auto overflow-x-auto">
                <ul>
                    <li>- Hey admins! Now you can add users from application! ⚒️</li>
                    <li>- We added changelog section to keep eye on versioning and past updates! 👀</li>
                    <li>- Added more responsiveness on screen resolutions! 📱</li>
                </ul>
            </description>
            <footer>
                Please report bugs on github!
                <div class="flex justify-between">
                    <h4>01/06/2023</h4>
                    <h3>v0.0.6x</h3>
                </div>
            </footer>
        </article>

        <article class="flex justify-between flex-col gap-5 max-w-[25rem] min-h-80 max-h-80 bg-gray-700 rounded-md p-5">
            <header>
                <h1 class="flex-1 font-medium text-xl">What's new in version 0.0.7x! 🥳</h1>
            </header>
            <description class="flex-auto overflow-x-auto">
                <ul>
                    <li>- Guess what! Yes you are right! Updating records is now available in admin panel! Hope this helps! ⚒️ </li>
                    <li>- Changing password on first time login? Sounds interesting! 😍 </li>
                    <li>- Fixed login redirect when trying to access login page from url when logged in 🔨</li>
                    <li title="(0x23011011)">- Introduced versioning system of application! In changelogs from now will be added build numbers of application on hover! 🧑‍💻</li>
                    <li title="(0x23011012)">- Added session timeouts on 5 minutes for security reasons ⚙️</li>
                    <li title="(0x23011016)">- Better table of users in admin panel ⚒️</li>
                    <li title="(0x23011107)">- When coming from HTTP, imidiate redirect to HTTPS to ensure security ⚙️</li>
                    <li title="(0x23011112)">- Added announcement banner! 😍</li>
                    <li title="(0x23011208)">- Major Security Fixes ⚙️</li>
                    <li title="(0x23011210)">- Fixed lot of bugs ⚙️</li>
                </ul>
            </description>
            <footer>
                Please report bugs on github!
                <div class="flex justify-between">
                    <h4>01/12/2023</h4>
                    <h3>v0.0.7x</h3>
                </div>
            </footer>
        </article>
    </aside>
</main>
