<main class="grid lg:grid-cols-2 md:grid-cols-2 grid-cols-1 gap-4 justify-items-center max-w-9xl pt-28 pb-8 m-auto">
    <article class="flex justify-between flex-col gap-5 w-[30rem] min-h-80 bg-gray-700 rounded-md p-5">
        <header>
            <h1 class="flex-1 font-medium text-xl">What's new in version 0.1.6a! 🥳</h1>
        </header>
        <description class="flex-auto">
                <li>Hey admins! Now you can add users from application! ⚒️</li>
                <li>We added changelog section to keep eye on versioning and past updates! 👀</li>
                <li>Added more responsiveness on screen resolutions! 📱</li>
                <br>
                Please report bugs on github!
        </description>
        <footer class="flex justify-between">
            <h4>1/6/2023</h4>
            <h3>v0.1.6a</h3>
        </footer>
    </article>
</main>