<?
if(!empty($_GET["request"]))
switch($_GET["request"]){
    case "login":
        $title = " | Login"; 
        break;

    case "home":
        $title = " | Home"; 
        break;
    
    case "dashboard":
        $title = " | Dashboard"; 
        break;

    case "changelog":
        $title = " | Changelog"; 
        break;

    case "admin":
        $title = " | Admin"; 
        break;

    default:
        $title = " | Home"; 
        break;
}
else
    $title = " | Home";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="assets/style/style.css" type="text/css">
    <link rel="stylesheet" href="assets/style/global.css" type="text/css">
    <link rel="icon" href="./favicon.ico">

    <script rel="preload" src="https://kit.fontawesome.com/46f2e8d43d.js" crossorigin="anonymous"></script>
    <script src="assets/scripts/functions.js"></script>
    <title>Q-Bit<?=$title?></title>
</head>
<body class="dark:bg-gray-900 dark:text-blue-50 flex flex-col min-h-screen">
<? 
    require_once "assets/navigation.phtml";
    include_once "functions/functions.php";
?>
