<main class="grid lg:grid-cols-4 md:grid-cols-3 grid-cols-1 gap-4 justify-items-center max-w-full pt-28 pb-8 px-[9.5vw]">
    <announcement class="flex justify-between flex-col col-span-1 md:col-span-3 lg:col-span-4 gap-5 text-black w-full min-h-[15rem] bg-holographic-texture bg-auto rounded-md p-5">
        <header class="max-h-7 flex items-center">
            <h1 class="flex-1 font-medium text-xl">ANNOUNCEMENT!</h1>
            <div onClick="closeThis(this);">
                <i class="fa-solid fa-xmark fa-xl"></i>
            </div>
        </header>
        <description class="flex-auto">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultricies sem sapien, sit amet molestie dui cursus id. Nam sed nunc tincidunt, mollis nisi sed, posuere nisi. Phasellus quis tellus scelerisque, congue augue et, volutpat felis. Nunc mattis ut velit id bibendum. Nam pharetra posuere leo, id sollicitudin lectus fermentum sed. Etiam purus ipsum, auctor ac orci vitae, aliquam aliquet augue. Curabitur condimentum elementum mauris dignissim faucibus. Praesent finibus, metus quis porttitor mollis, sapien lectus rhoncus ipsum, ornare dictum lorem nisi vitae ligula. Aenean aliquet elit vitae erat aliquet iaculis. Proin id tellus sem.
        </description>
        <footer class="flex justify-between">
            <h4>1/11/2023</h4>
            <h3>Jaroslav Maša</h3>
        </footer>
    </announcement>    


</main>