<main class="grid lg:grid-cols-4 md:grid-cols-3 grid-cols-1 gap-4 justify-items-center max-w-7xl pt-28 pb-8 m-auto">

    <article class="flex justify-between flex-col gap-5 w-72 min-h-80 bg-blue-700 rounded-md p-5">
        <header>
            <h1 class="flex-1 font-medium text-xl">Welcome to Q-Bit!</h1>
        </header>
        <description class="flex-auto">
            We are thrilled to celebrate the launch of the Q-Bit app! A huge thank you to everyone who has supported us along the way. Thank you for helping us bring this product to life. Here's to a bright future for the Q-Bit app! Thank you again for your support.
        </description>
        <footer class="flex justify-between">
            <h4>1/5/2023</h4>
            <h3>Jaroslav Maša</h3>
        </footer>
    </article>

    <article class="flex justify-between flex-col gap-5 w-72 min-h-80 bg-blue-500 rounded-md p-5">
        <header>
            <h1 class="flex-1 font-medium text-xl">Welcome to Q-Bit!</h1>
        </header>
        <description class="flex-auto">
            We are thrilled to celebrate the launch of the Q-Bit app! A huge thank you to everyone who has supported us along the way. Thank you for helping us bring this product to life. Here's to a bright future for the Q-Bit app! Thank you again for your support.
        </description>
        <footer class="flex justify-between">
            <h4>1/5/2023</h4>
            <h3>Jaroslav Maša</h3>
        </footer>
    </article>
    
    
    
</main>