<main class="grid-rows-4 grid-cols-4 gap-4 m-auto px-28 py-32">
    <article class="flex justify-between flex-col gap-5 w-72 h-80 bg-blue-700 rounded-md p-5">
        <header>
            <h1 class="flex-1 font-medium text-xl">Welcome to Q-Bit!</h1>
        </header>
        <description class="flex-auto">
            <p>I am so happy to announce that <b>Q-Bit</b> is in alfa state of build! Source code is available on my <a href="https://github.com/dxvil-exe/Q-Bit" target="_blank">GitHub</a>! Full Version should available in 2 months!</p>
        </description>
        <footer class="flex justify-between bottom-">
            <h4>1/5/2023</h4>
            <h3>Jaroslav Maša</h3>
        </footer>
    </article>
</main>