<?php
    $pageWasRefreshed = isset($_SERVER['HTTP_CACHE_CONTROL']) && $_SERVER['HTTP_CACHE_CONTROL'] === 'max-age=0';

    if($pageWasRefreshed ) unset($_SESSION["loginFailed"]);
    include("./functions/functions.php");
    include("./assets/navigation.phtml");
?>
<div class="h-screen flex">
    <form class="m-auto w-1/4 grid grid-rows-4 grid-cols-4 gap-4" method="post" action="login.php"> 
        <input type="text" autocomplete="username" name="username" id="username" rows="1" class="col-span-4 block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Username"></input>
        <input type="password" autocomplete="current-password" name="password" id="password" rows="1" class="col-span-4 block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Password"></input>
        <button type="submit" class="col-span-1 align-center px-5 py-2.5 text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">Login</button>
        <?httpWarning($errorIcon, $errorClass)?>
        <?(isset($_GET["failed"]) && $_GET["failed"] == true) ? failedLogin($errorIcon, $errorClass, $_GET["failed"]) : exit ?>
    </form>
</div>